# Generated by Django 3.2.1 on 2021-05-14 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='title', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(default='Mattress', max_length=255)),
                ('condition', models.CharField(default='Good', max_length=255)),
                ('brand', models.CharField(default='Brand', max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+911111111111', max_length=128, region=None)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('email', models.EmailField(blank=True, default='example@gmail.com', max_length=70)),
                ('product_image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('name', models.CharField(default='name', max_length=64)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
